### ISSUE TITLE
直接侧脸检测的？没有做人脸68点对齐？

### ISSUE THREAD

**Issue by xinsuinizhuan** [EdVince/PSGAN-NCNN#1]

**Comment by EdVince** [comment]
我刚刚README里面更新了一个知乎文章，可以去看看，PSGAN这个工作的人脸对齐比较特别，不是简单的显式对齐。

**Comment by xinsuinizhuan** [comment]
嗯嗯。就是没看看懂这里的对齐方式，也没看到相关的函数。这个知乎里面是5点对齐，想知道多点的对齐，68和98点的对齐

**Comment by EdVince** [comment]
68点的，PSGAN的原工作是用dlib做的，我为了方便使用用ncnn的模型替换了。
