### ISSUE TITLE
没有保存生成结果的按钮？

### ISSUE THREAD

**Issue by DWCTOD** [EdVince/PSGAN-NCNN#2]
你好，谢谢大佬的分享，不过没有在exe 中找到保存生成结果的按钮

**Comment by EdVince** [comment]
😂我没做这个功能，你有保存的需求吗？或者你可以尝试截个图也行。

**Comment by DWCTOD** [comment]
感觉还是有点需要的，因为现在生成的结果是被 resize 的，截图的话有点模糊的感觉

**Comment by EdVince** [comment]
我过几天给qt界面加个保存按钮，顺带把安卓app的版本也做出来好了

**Comment by EdVince** [comment]
已经更新了带保存功能的qt代码和程序了，可以到百度网盘上下载新的。

**Comment by DWCTOD** [comment]
太强了，谢谢大佬
