### ISSUE TITLE
闪退问题

### ISSUE THREAD

**Issue by DWCTOD** [EdVince/PSGAN-NCNN#3]
你好，好像输入的图片太小的话（小于256x256的时候），会出现闪退的问题。

**Comment by EdVince** [comment]
这么小的图像，细节也不够多，不推荐用，尽量还是用分辨率大一点的吧。闪退的话，这个可能得要查一查代码才知道，除了分辨率的问题，也有可能是人脸太偏，检测不到人脸，情况比较多。

**Comment by DWCTOD** [comment]
![cropped_face](https://user-images.githubusercontent.com/41478810/139792330-66b7319b-1e1d-45b6-8613-5dc248390550.png)
我输入这张图片就出问题了，人脸应该是能检测到的，我使用 dlib 切出来人脸的区域

**Comment by EdVince** [comment]
这个图片我测试了一下确实是会有问题，问题出在psgan.cpp文件里面的crop这个函数，crop出来的结果是人脸框超出图片的尺寸了，但是crop这个函数又臭又长，实在是不想改了，你可以尝试用“脸部”更加完整的图像来测试，例如这个图
![another](https://user-images.githubusercontent.com/18224516/140614661-71672d77-a59f-4d0e-ba19-1d2e8deb2cdb.jpg)

**Comment by DWCTOD** [comment]
好的哈，谢谢大佬
