### ISSUE TITLE
能不能多搞搞其他GAN的C++部署呀！！刚需啊。

### ISSUE THREAD

**Issue by hhuiwang** [EdVince/PSGAN-NCNN#4]
比如stylegan这种

**Comment by EdVince** [comment]
基本上大部分的GAN都是能部署的，但也有少部分是不行，但其实部署最麻烦的是做界面，特别是要互动的一些GAN。如果你们有什么需要的GAN可以留言一下，我看下合适的话就做一下。

**Comment by huanghehui** [comment]
stylegan能C++部署就好了。因为还涉及到一个属性编辑的问题，我自己比较菜。官方的TF模型转换onnx总是不成功，期待大神！！界面其实不太重要，又不是写成品给用户使用。能转换调用就很开心了

**Comment by hhuiwang** [comment]
> 



> 基本上大部分的GAN都是能部署的，但也有少部分是不行，但其实部署最麻烦的是做界面，特别是要互动的一些GAN。如果你们有什么需要的GAN可以留言一下，我看下合适的话就做一下。

stylegan 能 C++ 部署就好了。还涉及到属性编辑的问题，自己比较菜，从官方的TF模型转换总是不成功，期待大神。其实界面什么的不太纠结，能转换调用就已经很开心了。

**Comment by EdVince** [comment]
我记得stylegan的2开始就是pytorch的了吧，没必要继续用tensoflow的版本吧？
