### ISSUE TITLE
如何调用该exe文件实现多张妆容迁移后的图像？

### ISSUE THREAD

**Issue by limingzou-haha** [EdVince/PSGAN-NCNN#5]
楼主你好，非常感谢分享。我想要得到很多张妆容迁移后的图像用来做研究，如果一张张人工load图像是不现实的。我的代码能力不是很好，对matlab比较熟悉，所以我想到用matlab调用该exe文件生成妆容迁移图像，但是该exe文件的参数是图像，而matlab中传递的参数必须是文本标量，查阅了资料也无法解决。如果该exe文件的输入是图像的地址的话，应该是可以实现该exe文件的调用的。想问下楼主有没有其他方法可以调用该exe文件实现自动输入输出啊？感谢楼主啊！！！

**Comment by EdVince** [comment]
你有生成大量图像做研究的需要的话，还是跑原始PSGAN的pytorch代码比较好，我的这个实现在生成速度以及精度上都跟pytorch的差一点的。原始PSGAN工作的文档写的很详细，你按照走一遍应该也能跑起来了。

**Comment by limingzou-haha** [comment]
> 你有生成大量图像做研究的需要的话，还是跑原始PSGAN的pytorch代码比较好，我的这个实现在生成速度以及精度上都跟pytorch的差一点的。原始PSGAN工作的文档写的很详细，你按照走一遍应该也能跑起来了。

谢谢，那我还是跑原始代码吧，之前是想偷懒来着😂还是感谢啊😊
